# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - 6379:6379
    memcached:
          container_name: memcached
          image: memcached:alpine
          ports:
              - 11211:11211
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        container_name: nginx
        # маршрутизируем порты
        ports:
            - 127.0.0.1:80:80
            #- 127.0.0.1:443:443
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
            - redis
        environment:
            - TZ=Europe/Moscow
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        container_name: php
        # этот образ будет общаться с postgres
        links:
            - postgres
            - redis
            - memcached
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
        environment:
            - TZ=Europe/Moscow
    postgres:
        image: postgres:12.2
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - TZ=Europe/Moscow
            - PGTZ=Europe/Moscow
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/:/docker-entrypoint-initdb.d/
    adminer:
        image: adminer
        container_name: adminer
        depends_on:
            - postgres
        restart: always
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_DB_DRIVER: pgsql
            ADMINER_DEFAULT_DB_HOST: postgres